//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Gabriel_DBEntities : DbContext
    {
        public Gabriel_DBEntities()
            : base("name=Gabriel_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Law_Classification> Law_Classification { get; set; }
        public virtual DbSet<Law_Recording_Classification> Law_Recording_Classification { get; set; }
        public virtual DbSet<Model_Catalog> Model_Catalog { get; set; }
    }
}
