//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Law_Recording_Classification
    {
        public int ID { get; set; }
        public string STATE { get; set; }
        public string CONSENT { get; set; }
        public string AUTHORITY { get; set; }
        public string EXPLANATION_ADDITIONAL_INFORMATION { get; set; }
    }
}
